### ISSUE TITLE
博主您好，这个比赛的官网我在网上搜没找到，能提供一下当时的赛题描述么？感谢！

### ISSUE THREAD

**Issue by balance231** [wsysx123/YSXAnswer#1]

**Comment by wsysx123** [comment]
Just uploaded

https://github.com/wsysx123/AliyunContest2020/blob/master/%E9%AB%98%E6%A0%A1%E6%8C%91%E6%88%98%E8%B5%9B-%E8%B5%84%E6%BA%90%E8%B0%83%E5%BA%A6.pptx
